# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/abnmt/theater/models/category/fields.yaml

# Model Class name
modelClass: Abnmt\Theater\Models\Category

# Default redirect location
defaultRedirect: abnmt/theater/categories

# Create page
create:
    title: Create Category
    redirect: abnmt/theater/categories/update/:id
    redirectClose: abnmt/theater/categories

# Update page
update:
    title: Edit Category
    redirect: abnmt/theater/categories
    redirectClose: abnmt/theater/categories

# Preview page
preview:
    title: Preview Category