scopes:
    is_published:
        label: Скрыть не опубликованые
        type: checkbox
        scope: isPublished
    type:
        label: Тип
        modelClass: Abnmt\Theater\Models\Performance
        nameFrom: type
    is_normal:
        label: Обычные
        type: checkbox
        scope: isNormal
    is_archive:
        label: Архив
        type: checkbox
        scope: isArchive
    is_child:
        label: Детские
        type: checkbox
        scope: isChild