scopes:
    is_published:
        label: Скрыть не опубликованые
        type: checkbox
        scope: isPublished
    type:
        label: Категории
        modelClass: Abnmt\Theater\Models\PerformanceCategory
        nameFrom: title
    # is_normal:
    #     label: Обычные
    #     type: checkbox
    #     scope: isNormal
    # is_archive:
    #     label: Архив
    #     type: checkbox
    #     scope: isArchive
    # is_child:
    #     label: Детские
    #     type: checkbox
    #     scope: isChild