# ===================================
#  Relation Behavior Config
# ===================================

participation:
    label: Роли
    view:
        list: $/abnmt/theater/models/participation/performance_columns.yaml
        toolbarButtons: create|delete
    manage:
        list: $/abnmt/theater/models/participation/performance_columns.yaml
        form: $/abnmt/theater/models/participation/performance_fields.yaml
        recordsPerPage: 25

categories:
    label: Категории
    view:
        list: $/abnmt/theater/models/performancecategory/columns.yaml
        toolbarButtons: add|create|delete
    manage:
        list: $/abnmt/theater/models/performancecategory/columns.yaml
        form: $/abnmt/theater/models/performancecategory/fields.yaml
        recordsPerPage: 25