# ===================================
#  Relation Behavior Config
# ===================================

taxonomies:
    label:  Категории
    list: $/abnmt/theater/models/taxonomy/columns.yaml
    form: $/abnmt/theater/models/taxonomy/fields.yaml