# ===================================
#  Relation Behavior Config
# ===================================

# categories:
#     label: Категории
#     list: $/abnmt/theater/models/category/columns.yaml
#     form: $/abnmt/theater/models/category/fields.yaml
#     defaultSort: name
#     showSorting: true

performances:
    label: Спектакли
    list: $/abnmt/theater/models/performance/columns_min.yaml
    form: $/abnmt/theater/models/performance/fields.yaml
    defaultSort: title
    showSorting: true

people:
    label: Люди
    list: $/abnmt/theater/models/person/columns_min.yaml
    form: $/abnmt/theater/models/person/fields.yaml
    defaultSort: title
    showSorting: true

# performances:
#     label: Спектакли
#     view:
#         list: $/abnmt/theater/models/performance/columns_min.yaml
#         toolbarButtons: create|delete
#     manage:
#         list: $/abnmt/theater/models/performance/columns_min.yaml
#         form: $/abnmt/theater/models/performance/fields.yaml
#         recordsPerPage: 25

# people:
#     label: Люди
#     view:
#         list: $/abnmt/theater/models/person/columns_min.yaml
#         toolbarButtons: create|delete
#     manage:
#         list: $/abnmt/theater/models/person/columns_min.yaml
#         form: $/abnmt/theater/models/person/fields.yaml
#         recordsPerPage: 25
