# ===================================
#  Relation Behavior Config
# ===================================

participation:
    label: Роли
    view:
        list: $/abnmt/theater/models/participation/person_columns.yaml
        toolbarButtons: create|delete
    manage:
        list: $/abnmt/theater/models/participation/person_columns.yaml
        form: $/abnmt/theater/models/participation/person_fields.yaml
        recordsPerPage: 25