# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Person

# Model Form Field configuration
form: $/abnmt/theater/models/person/fields.yaml

# Model Class name
modelClass: Abnmt\Theater\Models\Person

# Default redirect location
defaultRedirect: abnmt/theater/people

# Create page
create:
    title: Create Person
    redirect: abnmt/theater/people/update/:id
    redirectClose: abnmt/theater/people

# Update page
update:
    title: Edit Person
    redirect: abnmt/theater/people
    redirectClose: abnmt/theater/people

# Preview page
preview:
    title: Preview Person