scopes:
    is_published:
        label: Скрыть не опубликованые
        type: checkbox
        scope: isPublished
    is_state:
        label: Штат
        type: checkbox
        scope: isState
    is_cooperate:
        label: Приглашенные
        type: checkbox
        scope: isCooperate