# ===================================
#  Relation Behavior Config
# ===================================

events:
    label: События
    view:
        list: $/abnmt/theater/models/event/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/abnmt/theater/models/event/fields.yaml
        recordsPerPage: 25