# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Playbill

# Model Form Field configuration
form: $/abnmt/theater/models/playbill/fields.yaml

# Model Class name
modelClass: Abnmt\Theater\Models\Playbill

# Default redirect location
defaultRedirect: abnmt/theater/playbill

# Create page
create:
    title: Create Playbill
    redirect: abnmt/theater/playbill/update/:id
    redirectClose: abnmt/theater/playbill

# Update page
update:
    title: Edit Playbill
    redirect: abnmt/theater/playbill
    redirectClose: abnmt/theater/playbill

# Preview page
preview:
    title: Preview Playbill