# ===================================
#  Relation Behavior Config
# ===================================

peopleterms:
    label:  Категории
    list: $/abnmt/theater/models/peopleterm/columns.yaml
    form: $/abnmt/theater/models/peopleterm/fields.yaml