# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Событие

# Model Form Field configuration
form: $/abnmt/theater/models/event/fields.yaml

# Model Class name
modelClass: Abnmt\Theater\Models\Event

# Default redirect location
defaultRedirect: abnmt/theater/events

# Create page
create:
    title: Новое событие
    redirect: abnmt/theater/events/update/:id
    redirectClose: abnmt/theater/events

# Update page
update:
    title: Изменение события
    redirect: abnmt/theater/events
    redirectClose: abnmt/theater/events

# Preview page
preview:
    title: Просмотр события